Enable end-to-end encryption
TypeFox/open-collaboration-tools pull request #14
Opened 2024-06-26 13:59 UTC by msujew

Refactors the messaging mechanism to include e2e encryption. Also refactors messages to use binary encoding (msgpack) during transmission to enable sending around binary payloads.

2024-06-27 10:12 UTC, msujew commented on packages/open-collaboration-vscode/src/collaboration-status-service.ts
>                  this.statusBarItem.text = '$(live-share) Share';
I've adjusted the status bar text to make it more unique.

2024-06-27 12:37 UTC, spoenemann approved these changes
Looks good to me. Great contribution! 🚀

2024-06-28 08:04 UTC, spoenemann requested changes
I need to revoke my approval. OpenPGP.js is LGPL licensed, which could have severe consequences for us and everyone using the project. We should look for an alternative, or find a way to integrate more loosely with the library (avoid a direct dependency).

2024-07-02 08:01 UTC, jonah-iden approved these changes
Works great even with 3 users in one room and all in all looks good to me

2024-07-02 09:49 UTC, msujew commented on packages/open-collaboration-rpc/src/connection.ts
> +                    Promise.resolve(result).then(async value => {
Yeah, in fact using the normal `try-catch` is actually way less code. Thanks!

2024-07-02 09:49 UTC, msujew commented on packages/open-collaboration-rpc/src/encryption.ts
> +            key: toBase64(await cryptoLib.publicEncrypt(keyBuffer, key.publicKey)),
It's an implementation detail (i.e. doesn't affect the working of the protocol) but I've added the caching now.

2024-07-02 11:44 UTC, jonah-iden commented
@msujew can confirm caching works great and it feels super fast

2024-07-02 11:46 UTC, spoenemann approved these changes
The license issue is resolved.

2024-07-02 12:37 UTC, merged